import { brandFor } from '../../_shared/brand.js';

const kela = brandFor('technology');

export const content = {
  brand: { name: `${kela.name}`, tagline: 'Cloud infrastructure, engineered for uptime.' },
  nav: [
    { label: 'Products', href: '#products' },
    { label: 'Regions', href: '#regions' },
    { label: 'Pricing', href: '#pricing' },
    { label: 'Docs', href: '#docs' },
  ],
  hero: {
    eyebrow: 'Global cloud platform — 28 regions',
    title: 'Infrastructure that scales with you.',
    sub: 'Compute, storage, and networking across five continents — provisioned in seconds, billed by the second, backed by a 99.99% uptime SLA.',
    ctaPrimary: 'Start free',
    ctaPrimaryHref: '#pricing',
    ctaSecondary: 'Explore the platform',
    ctaSecondaryHref: '#topology',
    status: [
      { label: 'All systems', value: 'Operational' },
      { label: 'P99 latency', value: '38 ms' },
      { label: 'Regions live', value: '28' },
    ],
  },
  topology: {
    eyebrow: 'Platform anatomy',
    title: 'One request, four layers deep.',
    body: 'Scroll through the stack — from the edge of the network down to a single pod — and see how every layer is engineered for resilience.',
    layers: [
      {
        id: 'edge',
        name: 'Edge',
        tag: 'Layer 01',
        desc: 'Requests land at the nearest of 140+ points of presence. Anycast routing, WAF, and DDoS absorption stop bad traffic before it ever reaches your origin.',
        stats: [
          { label: 'Points of presence', value: '140+' },
          { label: 'DDoS absorption', value: '2.1 Tbps' },
          { label: 'TLS handshake', value: '< 5 ms' },
        ],
      },
      {
        id: 'region',
        name: 'Region',
        tag: 'Layer 02',
        desc: 'A region is three physically separated availability zones on independent power and networking. Your data is replicated synchronously across all three.',
        stats: [
          { label: 'Regions', value: '28' },
          { label: 'AZs per region', value: '3' },
          { label: 'Inter-AZ latency', value: '< 2 ms' },
        ],
      },
      {
        id: 'cluster',
        name: 'Cluster',
        tag: 'Layer 03',
        desc: 'Workloads run on managed Kubernetes. Control planes are replicated across zones, nodes auto-heal, and upgrades roll without downtime.',
        stats: [
          { label: 'Node pools', value: 'Autoscale' },
          { label: 'Control plane SLA', value: '99.95%' },
          { label: 'Pod startup', value: '1.2 s' },
        ],
      },
      {
        id: 'pod',
        name: 'Pod',
        tag: 'Layer 04',
        desc: 'Your code, in a pod — isolated, observable, and schedulable anywhere on earth in under two seconds. This is where your application actually lives.',
        stats: [
          { label: 'Cold start', value: '< 2 s' },
          { label: 'vCPU sizes', value: '0.25–128' },
          { label: 'Observability', value: 'Built-in' },
        ],
      },
    ],
  },
  products: [
    {
      name: 'Compute',
      image: 'product-0',
      alt: 'Symmetric data-center hall with rows of server racks under cool light',
      tagline: 'C-Series instances',
      body: 'Burstable to 128 vCPUs with dedicated Nitro-grade isolation. From 0.25-vCPU dev boxes to GPU-heavy training rigs.',
      specs: ['C8 — 8 vCPU / 32 GB', 'G5 — 4× GPU / NVMe', 'B2 — burstable dev'],
      cta: 'Spin up an instance',
    },
    {
      name: 'Storage',
      image: 'product-1',
      alt: 'Server racks glowing blue in a dark data center, status LEDs in soft bokeh',
      tagline: `${kela.name} Object Store`,
      body: 'Eleven-nines durability with automatic erasure coding across three zones. Instant retrieval, no archive tiers to babysit.',
      specs: ['11×9s durability', '$0.023 / GB-month', 'Instant retrieval'],
      cta: 'Create a bucket',
    },
    {
      name: 'Networking',
      image: 'product-2',
      alt: 'Neatly organized color-coded network cables routed through a patch panel',
      tagline: `${kela.name} Fabric`,
      body: 'A private 4.2 Tbps backbone with anycast edge. VPCs, private link, and global load balancing in one control plane.',
      specs: ['4.2 Tbps backbone', 'Anycast edge', 'Global LB included'],
      cta: 'Design a VPC',
    },
    {
      name: 'Kubernetes',
      image: 'detail',
      alt: 'Macro of data-center cooling infrastructure, condensation on chilled pipes',
      tagline: `${kela.name} K8s`,
      body: 'Managed clusters with multi-AZ control planes, autoscaling node pools, and one-click upgrades — your YAML, our machinery.',
      specs: ['Multi-AZ control plane', 'Autoscaling pools', '1-click upgrades'],
      cta: 'Launch a cluster',
    },
  ],
  regions: {
    eyebrow: 'Global footprint',
    title: '28 regions. One control plane.',
    body: 'Deploy anywhere on the map — your configuration, policies, and observability follow your workloads, not the other way around.',
    list: [
      { name: 'N. Virginia', code: 'us-east-1', x: 25.5, y: 40 },
      { name: 'Ohio', code: 'us-east-2', x: 23.5, y: 35 },
      { name: 'Oregon', code: 'us-west-2', x: 12.5, y: 32 },
      { name: 'Toronto', code: 'ca-central-1', x: 26.5, y: 29 },
      { name: 'Mexico City', code: 'mx-central-1', x: 21.5, y: 52 },
      { name: 'São Paulo', code: 'sa-east-1', x: 32.5, y: 68 },
      { name: 'Ireland', code: 'eu-west-1', x: 45.5, y: 28 },
      { name: 'London', code: 'eu-west-2', x: 47.5, y: 25.5 },
      { name: 'Paris', code: 'eu-west-3', x: 48, y: 31 },
      { name: 'Frankfurt', code: 'eu-central-1', x: 50.5, y: 28 },
      { name: 'Milan', code: 'eu-south-1', x: 50.5, y: 35 },
      { name: 'Madrid', code: 'eu-south-2', x: 45, y: 36 },
      { name: 'Stockholm', code: 'eu-north-1', x: 52.5, y: 21 },
      { name: 'Tel Aviv', code: 'il-central-1', x: 57, y: 41 },
      { name: 'Bahrain', code: 'me-south-1', x: 60.5, y: 48 },
      { name: 'UAE', code: 'me-central-1', x: 61.5, y: 45.5 },
      { name: 'Cape Town', code: 'af-south-1', x: 53.5, y: 78 },
      { name: 'Mumbai', code: 'ap-south-1', x: 66.5, y: 52 },
      { name: 'Hyderabad', code: 'ap-south-2', x: 68, y: 55.5 },
      { name: 'Hong Kong', code: 'ap-east-1', x: 77.5, y: 50 },
      { name: 'Tokyo', code: 'ap-northeast-1', x: 82.5, y: 38 },
      { name: 'Seoul', code: 'ap-northeast-2', x: 80.5, y: 40.5 },
      { name: 'Osaka', code: 'ap-northeast-3', x: 84, y: 42 },
      { name: 'Singapore', code: 'ap-southeast-1', x: 73.5, y: 62 },
      { name: 'Jakarta', code: 'ap-southeast-3', x: 75.5, y: 64.5 },
      { name: 'Sydney', code: 'ap-southeast-2', x: 88, y: 76 },
      { name: 'Auckland', code: 'ap-southeast-4', x: 95, y: 87 },
      { name: 'Nairobi', code: 'af-east-1', x: 55.5, y: 63 },
    ],
  },
  metrics: [
    { value: 28, suffix: '', label: 'Regions worldwide', decimals: 0 },
    { value: 99.99, suffix: '%', label: 'Uptime SLA, trailing 12 months', decimals: 2 },
    { value: 4.2, suffix: ' Tbps', label: 'Private backbone capacity', decimals: 1 },
    { value: 38, suffix: ' ms', label: 'Global P99 edge latency', decimals: 0 },
  ],
  pricing: {
    eyebrow: 'Pay-as-you-go',
    title: 'Estimate your first month.',
    body: 'No commitments, no hidden tiers. Drag the sliders to a rough shape of your workload — this is what honest cloud pricing looks like.',
    rates: { vcpu: 0.0325, storage: 0.023, egress: 0.09 },
    sliders: [
      { id: 'vcpu', label: 'Compute', unit: 'vCPUs running 24/7', min: 1, max: 256, def: 8 },
      { id: 'storage', label: 'Storage', unit: 'GB of object storage', min: 10, max: 50000, def: 500 },
      { id: 'egress', label: 'Data transfer', unit: 'GB out to the internet', min: 0, max: 20000, def: 250 },
    ],
    note: 'Includes $200 of free credit for the first 60 days. Estimate before discount.',
    cta: 'Start free',
  },
  cta: {
    title: 'Deploy in minutes. Sleep through the night.',
    body: 'Spin up your first instance with $200 in free credit. No credit card until you decide to stay.',
    primary: 'Start free',
    secondary: 'Talk to sales',
  },
  contact: { email: `hello@${kela.domain}`, phone: '+1 (415) 555-0132' },
  docs: [
    { label: 'Quickstart guide', desc: 'From zero to deployed in 12 minutes.' },
    { label: 'API reference', desc: 'Every endpoint, every flag, every example.' },
    { label: 'Architecture center', desc: 'Reference topologies for real workloads.' },
  ],
  footer: {
    line: `© 2026 ${kela.name}, Inc. All systems operational.`,
    columns: [
      { title: 'Platform', links: ['Compute', 'Storage', 'Networking', 'Kubernetes', 'Edge'] },
      { title: 'Company', links: ['About', 'Careers', 'Blog', 'Press kit', 'Contact'] },
      { title: 'Legal', links: ['Privacy', 'Terms', 'DPA', 'Security', 'Status'] },
    ],
  },
};
