export const meta = {
  id: 'design-07-subscription',
  num: '07',
  name: 'Never Empty',
  tag: 'Subscription',
  style: 'Funnel-first subscription wizard with a reassurance-led voice',
  animation: 'Directional step slides, live numeric price tween, step-driven progress',
  typography: 'DM Serif Display + Plus Jakarta Sans',
  layout: 'Wizard-led funnel; builder panel with sticky summary; editorial support sections',
  mood: 'Fresh, reassuring, sunny — morning optimism',
  palette: 'Cream, forest green, terracotta',
  features: [
    '5-step plan builder (method, coffee, amount, grind, frequency)',
    'Live numeric price tween with clean mid-tween cancellation',
    'Directional step transitions (forward slides left, back slides right)',
    'Step-driven roastProgress bar (not scroll-driven)',
    '2-minute taste quiz with recommended plan',
    'First-delivery date with y-roll flip',
    'Reassurance microcopy as design material',
    'Sticky mobile summary bar',
  ],
  fonts: { display: 'DM Serif Display', body: 'Plus Jakarta Sans' },
  colors: { primary: '#22392C', accent: '#C96F3F' },
};
