export const meta = {
  id: 'design-08-ecommerce',
  num: '08',
  name: 'The Whole Shelf',
  tag: 'E-commerce',
  style: 'Shelf-density commerce with faceted discovery and transactional motion',
  animation: 'Quick-view FLIP modal, cart drawer, filter re-flow, quick-add morph',
  typography: 'Bodoni Moda + Inter',
  layout: 'Dense grid commerce; sticky faceted filter toolbar; promo hero',
  mood: 'Clean, confident, commercial — catalog honesty',
  palette: 'White, espresso, caramel',
  features: [
    'Sticky faceted filters (roast, taste, origin, price) with live counts',
    'Taste badges and roast badges on every card',
    'Quick-add on every card with success morph',
    'Quick-view FLIP modal (card image tweens to modal and back to the exact card)',
    'Cart drawer (demo) with subtotal',
    'Wishlist hearts with pop micro-interaction',
    'Grid re-flow under 0.6s on filter changes',
    'Search, sort, mobile filter drawer',
  ],
  fonts: { display: 'Bodoni Moda', body: 'Inter' },
  colors: { primary: '#2A2019', accent: '#C08B4D' },
};
