import { brandFor } from '../../_shared/brand.js';

const kela = brandFor('agency');

export const content = {
  brand: {
    name: kela.name,
    tagline: 'A maximalist creative collective',
  },
  nav: [
    { label: 'Work', href: '#work' },
    { label: 'Crew', href: '#crew' },
    { label: 'Services', href: '#services' },
    { label: 'Manifesto', href: '#manifesto' },
    { label: 'Say hi', href: '#contact' },
  ],
  hero: {
    eyebrow: 'Est. 2019 — pasting posters on every wall that will have us',
    title: 'Turn it up',
    titleAccent: 'to eleven',
    sub: `We are ${kela.name}: a collective of designers, printers and professional over-doers making posters, covers, merch and campaigns that refuse to whisper.`,
    cta: 'See the noise',
    ctaHref: '#work',
    stickers: [
      { text: '100% loud', rot: -4, tone: 'acid' },
      { text: 'no whispering', rot: 3, tone: 'ink' },
      { text: 'est. 2019', rot: -2, tone: 'paper' },
    ],
    videoAlt:
      'Hands slapping fresh posters onto a wheatpaste wall, layers colliding, pulling back on the dense wall',
  },
  cases: [
    {
      id: 'riot-season',
      img: 'work-1',
      alt: 'Bold maximalist album-cover artwork in acid yellow, magenta and black, exploding abstract shapes',
      title: 'Riot Season',
      client: 'Neon Prophets',
      year: '2026',
      kind: 'Tour poster series',
      blurb: 'Thirty cities, thirty posters, zero chill. Wheatpasted across three continents in one weekend.',
      rot: -3, top: '2%', left: '4%', w: 30, z: 4, tone: 'acid',
    },
    {
      id: 'velvet-static',
      img: 'work-2',
      alt: 'Festival crowd at dusk with confetti in the air and an acid-yellow stage glowing through haze',
      title: 'Velvet Static',
      client: 'Velvet Static',
      year: '2025',
      kind: 'Album cover + stage',
      blurb: 'The cover that started a mosh pit. The stage that ended one. Same night.',
      rot: 2, top: '6%', left: '56%', w: 38, z: 5, tone: 'ink',
    },
    {
      id: 'louder-fest',
      img: 'work-3',
      alt: 'Die-cut sticker sheets with bold abstract graphics in acid yellow, magenta, black and cream',
      title: 'Louder Fest 25',
      client: 'Louder Fest',
      year: '2025',
      kind: 'Festival identity',
      blurb: 'Identity, stage scrims, wristbands and 40,000 stickers. Nobody left unstuck.',
      rot: -2, top: '26%', left: '34%', w: 30, z: 6, tone: 'paper',
    },
    {
      id: 'peel-slowly',
      img: 'detail',
      alt: 'Hands tearing through layered wheatpasted posters, bright colors revealed underneath',
      title: 'Peel Slowly',
      client: 'City of Posters',
      year: '2025',
      kind: 'Street campaign',
      blurb: 'A campaign designed to be destroyed. The tearing IS the media plan.',
      rot: 3, top: '44%', left: '8%', w: 26, z: 7, tone: 'acid', magenta: true,
    },
    {
      id: 'wall-of-everything',
      img: 'hero',
      alt: 'Dense wall of layered wheatpasted posters with torn curling edges',
      title: 'Wall of Everything',
      client: 'Self-initiated',
      year: '2024',
      kind: 'Wheatpaste takeover',
      blurb: 'Our studio wall, rebuilt weekly. Come by and take a layer home.',
      rot: -3, top: '48%', left: '60%', w: 34, z: 8, tone: 'paper',
    },
    {
      id: 'sourmilk',
      img: null,
      title: 'Sourmilk Drop',
      client: 'Sourmilk Supply',
      year: '2026',
      kind: 'Merch drop',
      blurb: 'Tees, hoodies and a tote that sold out before lunch. Twice.',
      rot: 2, top: '66%', left: '18%', w: 26, z: 9, tone: 'ink',
      big: 'SOUR\nMILK',
    },
    {
      id: 'kazoo-kidz',
      img: null,
      title: 'Kazoo Kidz',
      client: 'Kazoo Kidz',
      year: '2024',
      kind: 'Kids fest posters',
      blurb: 'A family festival with the volume of a stadium show. Earplugs optional.',
      rot: -2, top: '70%', left: '52%', w: 24, z: 10, tone: 'acid',
      big: 'KAZOO\nKIDZ',
    },
    {
      id: 'midnight-rave',
      img: null,
      title: 'Midnight Rave',
      client: 'Warehouse 9',
      year: '2025',
      kind: 'Flyer set',
      blurb: 'Twelve flyers, one secret location, four thousand dancers.',
      rot: 3, top: '86%', left: '10%', w: 24, z: 11, tone: 'paper',
      big: 'MID\nNIGHT',
    },
    {
      id: 'sticker-bomb',
      img: null,
      title: 'Sticker Bomb Pack',
      client: 'Studio shop',
      year: '2026',
      kind: 'Shop drop',
      blurb: 'Sixty stickers. Zero subtlety. Ships worldwide, sticks anywhere.',
      rot: -3, top: '88%', left: '58%', w: 26, z: 12, tone: 'ink',
      big: 'STICK\nEM UP',
    },
  ],
  crew: [
    { name: 'Rafi Anwar', role: 'Founder / paste-up chief', note: 'Has wheatpaste in his veins. Probably.' },
    { name: 'June Osei', role: 'Art director', note: 'Believes white space is a rumor.' },
    { name: 'Marco Vidal', role: 'Type terrorist', note: 'Sets everything in caps. Apologizes never.' },
    { name: 'Priya Nair', role: 'Print wizard', note: 'Can smell a misregistered layer from a mile away.' },
    { name: 'Tom Becker', role: 'Motion menace', note: 'Makes still images nervous.' },
    { name: 'Ada Kowalski', role: 'Merch machine', note: 'Sold out three drops before breakfast.' },
  ],
  services: [
    { name: 'Posters', desc: 'Gig posters, tour series and wheatpaste takeovers — designed to be seen from a moving bus.' },
    { name: 'Album art', desc: 'Covers, gatefolds and vinyl packaging with enough energy to be heard.' },
    { name: 'Festival identity', desc: 'Full visual worlds: stages, scrims, wristbands, signage, the lot.' },
    { name: 'Merch & drops', desc: 'Tees, hoodies, stickers and objects people actually queue for.' },
    { name: 'Campaign chaos', desc: 'Street, social and stunt campaigns built for maximum collision.' },
    { name: 'Motion & titles', desc: 'Idents, title sequences and loops that never sit still.' },
    { name: 'Murals & street', desc: 'Walls, shutters and hoardings — the bigger the better.' },
    { name: 'Art direction', desc: 'We bring the loud. You bring the brief. Magic follows.' },
  ],
  manifesto: [
    'More is more.',
    'White space is a rumor.',
    'If it can be seen from a bus, ship it.',
    'Every layer is placed. Nothing is random.',
    'Loud is a discipline, not an accident.',
  ],
  contact: {
    eyebrow: 'Got a wall? A tour? A wild idea?',
    title: 'Shout at us',
    email: `hello@${kela.domain}`,
    phone: '+91 98765 43210',
    address: 'Studio 4, Printworks Lane, Bengaluru',
    hours: 'Mon–Fri, 10am–loud',
    socials: [
      { label: 'Instagram', href: `https://instagram.com/${kela.instagram}` },
      { label: 'TikTok', href: 'https://tiktok.com' },
      { label: 'X', href: 'https://x.com' },
    ],
    note: 'We reply within two working days. Usually louder than expected.',
  },
  footer: {
    line: `© 2026 ${kela.name}. All noise reserved.`,
    colophon: 'Designed at maximum volume. Set in Syne & Work Sans.',
  },
};
