import { brandFor } from '../../_shared/brand.js';

const kela = brandFor('fashion');

export const content = {
  brand: {
    name: kela.name,
    tagline: 'Bridal couture, stitched in ceremony',
    est: 'Est. 1998 — Kala Ghoda, Mumbai',
  },
  nav: ['The Bridal Edit', 'Trousseau', 'Craft', 'Atelier'],
  hero: {
    eyebrow: `${kela.name} · Bridal Couture`,
    title: 'Worn like a vow',
    sub: 'Bridal lehengas and trousseaus cut in kumkum maroon and sewn with zari — by private appointment only.',
    ctaPrimary: 'Book Your Appointment',
    ctaSecondary: 'Build Your Trousseau',
    note: 'Order 8–10 weeks before the wedding',
  },
  chapters: [
    {
      name: 'Ivory',
      tint: '#F3E3C2',
      ceremony: 'The Engagement',
      title: 'The Ivory Hour',
      copy: 'Champagne silk and pearl dabka for the engagement — whisper-weight zari that photographs like morning light.',
      fabric: 'Banarasi silk · pearl dabka',
      hours: 140,
      price: 96000,
      key: 'chapter-ivory',
    },
    {
      name: 'Blush',
      tint: '#E4A794',
      ceremony: 'The Sangeet',
      title: 'Sangeet, in Blush',
      copy: 'A twirl-built lehenga for the sangeet — blush zardozi that moves when she does, never outshines her.',
      fabric: 'Georgette · blush zardozi',
      hours: 320,
      price: 185000,
      key: 'chapter-blush',
    },
    {
      name: 'Gold',
      tint: '#C6A15B',
      ceremony: 'The Pheras',
      title: 'Pheras in Gold',
      copy: 'The wedding lehenga: hand-set zardozi, dabka and nakshi over raw silk. The piece the house is known for.',
      fabric: 'Raw silk · zardozi & dabka',
      hours: 480,
      price: 245000,
      key: 'chapter-gold',
    },
    {
      name: 'Crimson',
      tint: '#7A1F26',
      ceremony: 'The Reception',
      title: 'Crimson, After Midnight',
      copy: 'A reception trousseau in deep crimson velvet — the jewels, the silk, the attar; everything in one casket.',
      fabric: 'Velvet · antique zari border',
      hours: 210,
      price: 150000,
      key: 'chapter-crimson',
    },
  ],
  trousseau: {
    title: 'The Trousseau Builder',
    sub: 'Choose one look per ceremony. Your shortlist travels with you to the appointment — or to your family on WhatsApp.',
    cta: 'Send Shortlist on WhatsApp',
    empty: 'Tap a ceremony above to add its look to your shortlist.',
    pieces: [
      { ceremony: 'Engagement', name: 'Ivory Engagement Silk', fabric: 'Banarasi silk · pearl dabka', hours: 140, price: 96000, key: 'product-0' },
      { ceremony: 'Sangeet', name: 'Blush Sangeet Lehenga', fabric: 'Georgette · blush zardozi', hours: 320, price: 185000, key: 'product-1' },
      { ceremony: 'Wedding', name: 'Gold Pheras Lehenga', fabric: 'Raw silk · zardozi & dabka', hours: 480, price: 245000, key: 'product-2' },
      { ceremony: 'Reception', name: 'Crimson Reception Trousseau', fabric: 'Velvet · antique zari border', hours: 210, price: 150000, key: 'product-2' },
    ],
  },
  craft: {
    eyebrow: 'The Craft',
    title: 'A single motif, nine days',
    body: `Zardozi, dabka, gota patti — three embroideries, one adda frame, forty years of hands. Every ${kela.name} lehenga carries the hours inside its hem, counted and signed by the karigar who stitched it.`,
    quote: 'The thread does not hurry. Neither do we.',
    quoteBy: `Master Karigar, ${kela.name} Atelier`,
    swatches: [
      { name: 'Zardozi', note: 'Gold-wrapped thread, couched by hand' },
      { name: 'Dabka', note: 'Coiled wire, cut and sewn one piece at a time' },
      { name: 'Gota Patti', note: 'Appliqué ribbon, pressed into petals' },
      { name: 'Nakshi', note: 'Fine wirework, the quietest glint' },
    ],
  },
  visit: {
    eyebrow: 'Private Appointments',
    title: 'Your hour, unhurried',
    body: 'One bride, one stylist, one hour. In-store in Kala Ghoda, on video call for families abroad, or a home trial in select cities.',
    types: [
      { name: 'In-Store', note: 'Kala Ghoda atelier', mins: 60 },
      { name: 'Video Call', note: 'For NRI families', mins: 30 },
      { name: 'Home Trial', note: 'Select cities', mins: 90 },
    ],
    slots: ['11:00', '13:00', '16:00', '18:30'],
    confirmTitle: 'The hour is yours',
    confirmBody: 'Our stylist will call to confirm your appointment within the day.',
    faq: [
      { q: 'How far ahead should I order?', a: 'Eight to ten weeks before the wedding. Rush couture in four is possible for select silhouettes.' },
      { q: 'Do you alter for fit?', a: 'Three fittings are included — first, mid-work, and a final a week before the ceremony.' },
      { q: 'Can my family join a video appointment?', a: 'Yes. We hold the call until every voice that matters has weighed in.' },
    ],
  },
  atelier: {
    eyebrow: 'The Atelier',
    title: 'A house of maroon and gold',
    body: 'Since 1998, our atelier on Rampart Row has dressed brides the way ceremonies deserve — slowly, by hand, with the family in the room. Marigold on the door, silk on the frame, chai always.',
    notes: ['Master karigars, forty years at the adda', 'Silk Mark certified zari', 'Private rooms for the family'],
  },
  contact: {
    email: `appointments@${kela.domain}`,
    phone: '+91 22 4890 1234',
    whatsapp: '912248901234',
    address: '14 Rampart Row, Kala Ghoda, Mumbai 400001',
    hours: 'Tue–Sun, 11am–8pm · by appointment',
    instagram: `https://instagram.com/${kela.instagram}`,
  },
  footer: {
    line: `${kela.name} — bridal couture, stitched in ceremony.`,
    note: 'Nothing here is discounted. Some things should never be.',
  },
};
