import { brandFor } from '../../_shared/brand.js';

const kela = brandFor('hotel');

export const content = {
  brand: {
    name: `${kela.name}`,
    tagline: 'Wellness, at the pace of water',
  },
  nav: [
    { label: 'The Pause', href: '#story' },
    { label: 'Programs', href: '#programs' },
    { label: 'Therapies', href: '#therapies' },
    { label: 'The Space', href: '#space' },
    { label: 'A Day Here', href: '#day' },
    { label: 'Visit', href: '#visit' },
  ],
  hero: {
    eyebrow: 'A wellness retreat · Western Ghats',
    title: 'Arrive still. Leave lighter.',
    cta: 'Begin',
    ctaHref: '#booking',
  },
  pause: {
    eyebrow: 'The pause',
    title: 'We measure a stay in breaths, not nights.',
    body: [
      `Most retreats fill your days. We empty them — gently. No schedules shouted across a lawn, no forty activities before lunch. ${kela.name} is built around one idea: the body already knows how to recover. It only needs quiet, warmth, and time.`,
      'Days here move with the light. Mornings begin before the mist lifts. Afternoons are for the pool, the garden, or nothing at all. Evenings end early, the way they should.',
      'You will not leave with a certificate. You will leave with slower mornings.',
    ],
    principles: [
      { title: 'Stillness first', text: 'Silence is kept across the estate until 9 am. Phones rest in your room.' },
      { title: 'Warmth always', text: 'Hot stone, warm oil, warm water. Everything here arrives at body temperature.' },
      { title: 'Nothing forced', text: 'Every session is an invitation. Skip anything. Sleep instead. That counts.' },
    ],
  },
  programs: [
    {
      id: 'arrival',
      name: 'The Arrival',
      days: 3,
      price: 78000,
      tagline: 'Unwind, sleep, breathe.',
      desc: 'Three days to come down from the speed of your life. Sleep deepens, shoulders drop, and the mind finally goes quiet.',
      includes: [
        'Welcome consultation & dosha reading',
        'Daily 60-minute Abhyanga massage',
        'Dawn yoga & evening sound bath',
        'All meals — sattvic, served slow',
        'One Shirodhara session',
      ],
      rhythm: [
        { t: 'Dawn', label: 'Yoga & breathwork' },
        { t: 'Morning', label: 'Treatment & rest' },
        { t: 'Afternoon', label: 'Pool, garden, or nothing' },
        { t: 'Evening', label: 'Sound bath & early night' },
      ],
    },
    {
      id: 'turning',
      name: 'The Turning',
      days: 5,
      price: 124000,
      tagline: 'Reset the nervous system.',
      desc: 'Five days is where the change becomes durable. Treatments deepen, the body starts trusting the quiet, and old tension lets go.',
      includes: [
        'Everything in The Arrival',
        'Two Shirodhara sessions',
        'Forest salt scrub & steam ritual',
        'Private yoga consultation',
        'Guided forest walk at dawn',
        'A take-home practice plan',
      ],
      rhythm: [
        { t: 'Dawn', label: 'Yoga, breathwork & journal' },
        { t: 'Morning', label: 'Two treatments, unhurried' },
        { t: 'Afternoon', label: 'Forest walk or deep rest' },
        { t: 'Evening', label: 'Fire-side sound bath' },
      ],
    },
    {
      id: 'becoming',
      name: 'The Becoming',
      days: 7,
      price: 168000,
      tagline: 'Return to yourself.',
      desc: 'A full week. Enough time for the nervous system to rewrite its defaults — and for you to remember what an unhurried mind feels like.',
      includes: [
        'Everything in The Turning',
        'Daily private treatments',
        'Hot stone ritual & herbal poultice',
        'One-on-one breathwork sessions',
        'A personal menu with our chef',
        'A follow-up call after 30 days',
      ],
      rhythm: [
        { t: 'Dawn', label: 'Private yoga on the deck' },
        { t: 'Morning', label: 'Treatment & consultation' },
        { t: 'Afternoon', label: 'Stillness — fully scheduled' },
        { t: 'Evening', label: 'Ritual bath & early night' },
      ],
    },
  ],
  programImages: [
    { imgKey: 'product-0', alt: 'Hot stones resting on a treatment table in soft morning light, folded linen beside them' },
    { imgKey: 'product-1', alt: 'Open-air meditation pavilion in a green garden at dawn, sheer curtains drifting' },
    { imgKey: 'product-2', alt: 'A practitioner in seated yoga pose on a wooden deck at sunrise, seen from behind at a distance' },
  ],
  therapies: {
    eyebrow: 'Therapies',
    title: 'The treatment menu',
    note: 'All treatments include warm towels, herbal tea, and as much quiet as you want afterwards.',
    items: [
      { name: 'Abhyanga', duration: '60 min', price: 6500, desc: 'Warm herbal oil, four hands, slow strokes. The signature.' },
      { name: 'Shirodhara', duration: '45 min', price: 7200, desc: 'A steady stream of warm oil across the forehead. Profoundly stilling.' },
      { name: 'Hot stone ritual', duration: '90 min', price: 9800, desc: 'Basalt stones, warm oil, deep muscle release.' },
      { name: 'Forest salt scrub', duration: '45 min', price: 5400, desc: 'Mineral salt, eucalyptus steam, rain-shower rinse.' },
      { name: 'Sound bath', duration: '60 min', price: 4800, desc: 'Bowls, gongs, and sixty minutes of lying down.' },
      { name: 'Private yoga', duration: '60 min', price: 3600, desc: 'One teacher, your breath, the dawn deck.' },
    ],
  },
  space: {
    eyebrow: 'The space',
    title: 'Stone, water, green.',
    intro: 'Eleven acres in the hills. Travertine underfoot, frangipani overhead, and water everywhere — still, warm, and waiting.',
    blocks: [
      { title: 'The still pool', text: 'Twenty-five metres of dawn-cold water that nobody hurries you out of. Swim at first light, when the surface is glass.' },
      { title: 'The frangipani garden', text: 'A walled garden for doing nothing properly. Hammocks, stone benches, and the smell of flowers after rain.' },
      { title: 'The stone bathhouse', text: 'Steam, plunge, rest — repeated slowly. Attendants appear exactly when needed and never otherwise.' },
      { title: 'The dawn deck', text: 'East-facing, above the mist line. Yoga here starts before the sun, and ends when it arrives.' },
    ],
    poolAlt: 'The infinity pool at dawn, its surface perfectly still and mirroring the pale sky',
    gardenAlt: 'Water ripples in macro, concentric rings expanding across a pale pool surface',
  },
  day: {
    eyebrow: 'A day here',
    title: 'The hours, gently.',
    schedule: [
      { time: '05:30', label: 'Wake, unhurried', text: 'No alarm. Birds handle it.' },
      { time: '06:00', label: 'Dawn yoga', text: 'On the deck, above the mist.' },
      { time: '07:30', label: 'Warm breakfast', text: 'Eaten slowly, in silence until nine.' },
      { time: '09:00', label: 'Treatment', text: 'Your therapist finds you. Not the other way round.' },
      { time: '12:30', label: 'Lunch in the garden', text: 'Sattvic, seasonal, unhurried.' },
      { time: '15:00', label: 'The pool, or a nap', text: 'Both are on the program.' },
      { time: '17:30', label: 'Evening walk or sound bath', text: 'The light does most of the work.' },
      { time: '19:00', label: 'Dinner by lamplight', text: 'Early, warm, quiet.' },
      { time: '21:00', label: 'Sleep', text: 'Early. Deep. Non-negotiable.' },
    ],
  },
  booking: {
    eyebrow: 'Begin',
    title: 'Choose your pace.',
    body: 'Tell us when. We will take care of the rest — the room, the meals, the treatments, the quiet.',
    perGuestExtra: 9000,
    extraNote: 'Rates cover the full program for two guests, including stay and all meals. Each additional guest adds a flat supplement for the stay.',
    submit: 'Request to book',
    confirmNote: 'We reply within a day — slowly, but personally.',
  },
  practical: {
    eyebrow: 'Practical',
    title: 'Good to know.',
    items: [
      { title: 'Arriving', text: 'The nearest airport is two hours by car; we send a driver who does not talk unless you do.' },
      { title: 'Check-in', text: 'From 2 pm, unhurried. Check-out at 11 am, with lunch if your flight is later.' },
      { title: 'What to bring', text: 'Almost nothing. White cotton clothing is provided; the weather does the rest.' },
      { title: 'Seasons', text: 'October to March is clearest. The monsoon is beautiful and half the price.' },
      { title: 'Staying connected', text: 'Wi-Fi reaches every room. Silence is kept estate-wide until 9 am.' },
    ],
  },
  contact: {
    email: `stay@${kela.domain}`,
    phone: '+91 98220 45678',
    address: `${kela.name}, Mullayanagiri Road, Chikkamagaluru, Karnataka 577101`,
  },
  footer: {
    line: `© 2026 ${kela.name}`,
    colophon: 'Built slowly, like everything here.',
  },
};
